--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/FPS
build-by-default: true
projects:
  FPS:
    path: ""
    icon: "icon.png"
    excludeDirs:
      - .github
    excludeFiles:
      - .gitignore
    libs:
      - src: LatamPMDevs/libCustomPack/libCustomPack
        version: ^1.0.1
      - src: LatamPMDevs/FormAPI/libFormAPI
        version: ^2.1.1
...
